;; -*- coding: utf-8-unix -*-
;; History for SLIME REPL. Automatically written.
;; Edit only if you know what you're doing
("(iterate:iter
	   (print \"hello world!\"))" "(require 'iterate)" "(ql:quickload \"iterate\")" "(ql:quickload \"iter\")" "(ql:quicklooad \"iter\")" "(asdf:load-system
	  'cl-pocketsphinx-test)" "(setf filey (ps-posix:fopen ps-user::*file-to-be-decoded* \"rb\"))" "ps-user::*file-to-be-decoded*" "ps-user:*file-to-be-decoded*" "(require 'asdf)" "(asdf:load-system 'ps-pocketsphinx-test)" "asdf:*source-registry-parameter*" "(asdf:load-system :ps-pocketsphinx-test)" "(require \"asdf\")" "(asdf:registered-systems)" "(asdf:registered-systems
	  )" "(asdf:load-system:ps-pocketsphinx-test)" "(asdf:compile-system :cl-pocketsphinx-test)" "(asdf:compile-system :ps)" "(asdf:retry)" "(asdf:load-system 'cl-pocketsphinx-test)" "(ps-posix:fclose #.(SB-SYS:INT-SAP #X7FFFF00263C0))" "(ps-posix:close #.(SB-SYS:INT-SAP #X7FFFF00263C0))" "(ps-posix:fopen ps-user::*file-to-be-decoded* \"rb\")" "(ps-user::*file-to-be-decoded*)" "(setf tfile (ps-posix:fopen \"config.txtt\" \"rb\")
	       )" "(ps-posix:fclose #)" "(ps-posix:fopen \"config.txt\" \"rb\")" "(asdf:load-system 'cl-pocketsphinx-test :force t)" "(delete-package :pocketsphinx-user)" "1" "(asdf:load-system 'cl-pocketsphinx-tests)" "(exit)" "(load \"scratch.lisp\")" "(asdf:load-system 'cl-pocketsphinx)" "(in-package :cl-user)" "(in-package :sb-syss
		    )" "(in-package :sb-sys)")